// =============================================================================
// PDF Generation using jsPDF
// =============================================================================

const { jsPDF } = require('jspdf');

/**
 * Generate a professional PDF document
 */
async function generatePDF(title, content) {
  try {
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // Header
    doc.setFillColor(91, 45, 142); // Purple brand color
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(title || 'ByrdHouse Document', 20, 25);

    // Footer
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by ByrdHouse • ${new Date().toLocaleDateString()}`, 20, 290);

    // Content
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    
    const lines = content.split('\n');
    let y = 55;
    const pageHeight = 280;
    const margin = 20;
    const lineHeight = 7;

    for (const line of lines) {
      if (y > pageHeight) {
        doc.addPage();
        y = 20;
        doc.setFontSize(10);
        doc.text(`Continued from previous page — ${title}`, margin, y);
        y += 10;
        doc.setFontSize(11);
      }
      
      const linesWrapped = doc.splitTextToSize(line, 210 - 2 * margin);
      for (const l of linesWrapped) {
        if (y > pageHeight) {
          doc.addPage();
          y = 20;
        }
        doc.text(l, margin, y);
        y += lineHeight;
      }
    }

    // Return as base64 PDF
    const pdfBase64 = doc.output('arraybuffer');
    const buffer = Buffer.from(pdfBase64).toString('base64');
    
    return {
      pdfUrl: `data:application/pdf;base64,${buffer}`,
      status: 'success',
      title
    };

  } catch (error) {
    console.error('[PDF ERROR]', error.message);
    throw new Error(`PDF generation failed: ${error.message}`);
  }
}

module.exports = { generatePDF };